### PR TITLE
fix permission on iOS 14

### PR DESCRIPTION
**Pull request by Ralph-Li**
## Description

* upgrade `image_picker` to 0.7.5
* fix permission issue with `PHPicker` on iOS 14

### CODE REVIEW

**Comment by b-ray** [comment]
Sorry @Ralph-Li but I think this doesn't look right.
We should:
- Update master branch in this repo with upstream (it's currently 2 years behind)
- Check out the exact version you started from (I guess either master, or the tag of the version you started with)
- Then create a PR with only you changes starting from the above state.

If we do that, we can potentially contribute the changes back to the flutter repo, if they allow it.

@danybuoy could you please sanity check my thinking here?

**Comment by danybuoy** [comment]
> Sorry @Ralph-Li but I think this doesn't look right.
> We should:
> - Update master branch in this repo with upstream (it's currently 2 years behind)
> - Check out the exact version you started from (I guess either master, or the tag of the version you started with)
> - Then create a PR with only you changes starting from the above state.
> 
> If we do that, we can potentially contribute the changes back to the flutter repo, if they allow it.
> 
> @danybuoy could you please sanity check my thinking here?

Sounds good to me if you think this is the best way to manage this repo.

**Comment by Ralph-Li** [comment]
@danybuoy could you update master to the latest version from upsteam first?

**Comment by danybuoy** [comment]
Erm sure. Let me double check with @b-ray first

**Comment by danybuoy** [comment]
@Ralph-Li please fix up the conflicts if you can :)

**Pull request closed without merging**
